settings:
  title: 'Status Page'
  url: 'https://cfstatus.nonoidea.com/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:    
  - id: gdrive-omgd # unique identifier
    name: google-drive omgd
    description: 'google-drive omgd 团队盘' # default=empty
    url: 'https://gd.nonoidea.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
       
  - id: cfblog.10244201.xyz
    name: cfblog Serverless blog on CloudFlare博客
    url: 'https://cfblog.10244201.xyz/'
    method: GET
    expectStatus: 200
       
  - id: easyimage.nine.im
    name: 自建图床 永久 easyimage
    url: 'https://easyimage.nine.im/'
    method: GET
    expectStatus: 200
    
  - id: nezha.nonoidea.com
    name: nezha all machines
    url: 'https://nezha.nonoidea.com/'
    method: GET
    expectStatus: 200
    
#  - id: h1000v2eu.herokuapp.com
#    name: v2 h1000v2us.herokuapp
#    url: 'https://h1000v2eu.herokuapp.com/'
#    method: GET
#    expectStatus: 404
