settings:
  title: 'Status Page'
  url: 'https://cfstatus.nonoidea.com/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:    
  - id: gdrive-omgd # unique identifier
    name: google-drive omgd
    description: 'google-drive omgd 团队盘' # default=empty
    url: 'https://gd.nonoidea.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: www-linear-vc
    name: linear
    url: 'https://www.linear.vc/'
    method: GET
    expectStatus: 200

  - id: sk.ck.mk
    name: sk.ck.mk
    url: 'https://sk.ck.mk'
    method: GET
    expectStatus: 200

  - id: bit-lava-lake.cloud.okteto.net
    name: bit-lava-lake.cloud.okteto.net
    url: 'https://bit-lava-lake.cloud.okteto.net'
    method: GET
    expectStatus: 200
 
  - id: cloudreve-lava-lake.cloud.okteto.net
    name: cloudreve-lava-lake.cloud.okteto.net
    url: 'https://cloudreve-lava-lake.cloud.okteto.net'
    method: GET
    expectStatus: 200
    
  - id: cfdownloader.nonoidea.com
    name: cfdownloader Serverless通过CloudFlare网络加速加载特定文件
    url: 'https://cfdownloader.nonoidea.com'
    method: GET
    expectStatus: 200
        
  - id: cfblog.10244201.xyz
    name: cfblog Serverless blog on CloudFlare博客
    url: 'https://cfblog.10244201.xyz/'
    method: GET
    expectStatus: 200
        
  - id: cpic.10244201.xyz
    name: cpic v3 on buyvm lax 
    url: 'https://cpic.10244201.xyz/'
    method: GET
    expectStatus: 200
            
  - id: odpub.nonoidea.com
    name: odpub.nonoidea => heroku => od-xyze3m3
    url: 'https://odpub.nonoidea.com/'
    method: GET
    expectStatus: 200     
  
  - id: lk.ck.mk
    name: lk.ck.mk shorten links by CloudFlare serverless
    url: 'https://lk.ck.mk/'
    method: GET
    expectStatus: 200
    
  - id: cfp.10244201.xyz
    name: CloudFlare Partner cfp.10244201
    url: 'https://cfp.10244201.xyz/'
    method: GET
    expectStatus: 200

 - id: nezha.nonoidea.com
    name: nezha all machines
    url: 'https://nezha.nonoidea.com/'
    method: GET
    expectStatus: 200
